# Generated by Django 3.0.3 on 2020-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_userinfo_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portfolio',
            field=models.URLField(),
        ),
    ]
