# Generated by Django 3.0.3 on 2020-07-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='portfolio',
        ),
    ]
